version: '3.8'

services:
    postgres-dev:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: elegis-dev
        ports:
            - "5432:5432"
    
#    postgres-prod:
#        image: postgres:latest
#        environment:
#            POSTGRES_USER: postgres
#            POSTGRES_PASSWORD: 123456
#            POSTGRES_DB: elegis-prod
#        ports:
#            - "5433:5432"
#        depends_on:
#            - postgres-dev

#        networks:
#            - mynetwork
    
#    mongodb:
#        image: mongo:latest
#        ports:
#            - "27017:27017"
#        networks:
#            - mynetwork
#
#    rabbitmq:
#        image: rabbitmq:3-management
#        ports:
#            - "5672:5672"
#            - "15672:15672"
#        networks:
#            - mynetwork
#
#    productsapi:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        ports:
#            - "8082:8082"
#        depends_on:
#            - postgres
#            - mongodb
#            - rabbitmq
#        networks:
#            - mynetwork

#networks:
#    mynetwork:
#        driver: bridge